# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 09:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(max_length=50, verbose_name='NIP')),
                ('pendidikan', models.CharField(max_length=150, verbose_name='Pendidikan')),
                ('instansi', models.TextField(verbose_name='Nama Lengkap Instansi')),
                ('instansi_kode', models.CharField(max_length=20, verbose_name='Singkatan Instansi')),
                ('pangkat', models.TextField(verbose_name='Pangkat/Golongan Ruang/TMT')),
                ('jabatan', models.CharField(max_length=150, verbose_name='Jabatan')),
                ('jenjang', models.CharField(choices=[('', '----'), ('Pertama', 'Perekayasa Pertama'), ('Muda', 'Perekayasa Muda'), ('Madya', 'Perekayasa Madya'), ('Utama', 'Perekayasa Utama')], default='', max_length=10, verbose_name='Jenjang Perekayasa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Personil')),
            ],
            options={
                'verbose_name_plural': 'Profil',
            },
        ),
    ]
