# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-13 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, verbose_name='Nama kategori')),
                ('slug', models.SlugField(verbose_name='Slug')),
            ],
            options={
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Kegiatan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255, verbose_name='Nama kegiatan')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('kapan_dibuat', models.DateField(auto_now_add=True, verbose_name='Kapan dibuat')),
                ('kode', models.CharField(max_length=200, verbose_name='Kode')),
                ('referensi', models.TextField(verbose_name='Referensi')),
                ('kategori_kegiatan', models.ManyToManyField(to='utama.Kategori', verbose_name='Kategori')),
            ],
            options={
                'ordering': ['kapan_dibuat'],
            },
        ),
    ]
