# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-16 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utama', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kegiatan',
            name='kategori_kegiatan',
            field=models.ManyToManyField(blank=True, to='utama.Kategori', verbose_name='Kategori'),
        ),
    ]
