# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-20 04:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utama', '0002_auto_20160616_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=150, verbose_name='Nama format')),
                ('formasi', models.TextField(verbose_name='Kode dokumen')),
            ],
        ),
        migrations.AlterModelOptions(
            name='kegiatan',
            options={'ordering': ['-kapan_dibuat']},
        ),
        migrations.AddField(
            model_name='format',
            name='format_kegiatan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utama.Kegiatan', verbose_name='Kegiatan'),
        ),
    ]
