# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utama', '0005_personil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personil',
            name='peran',
            field=models.CharField(choices=[('', '----'), ('TS', 'Technical Staff'), ('ES', 'Engineering Staff'), ('L', 'Leader'), ('GL', 'Group Leader'), ('CE', 'Chief Engineering'), ('ACE', 'Assistant Chief Engineering'), ('PM', 'Program Manager'), ('PD', 'Program Director')], default='', max_length=3, verbose_name='Peran'),
        ),
    ]
