# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 09:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utama', '0006_auto_20160624_1344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='format',
            options={'verbose_name_plural': 'Format'},
        ),
        migrations.AlterModelOptions(
            name='kategori',
            options={'ordering': ['nama'], 'verbose_name_plural': 'Kategori'},
        ),
        migrations.AlterModelOptions(
            name='kegiatan',
            options={'ordering': ['-kapan_dibuat'], 'verbose_name_plural': 'Kegiatan'},
        ),
        migrations.AlterModelOptions(
            name='personil',
            options={'ordering': ['index'], 'verbose_name_plural': 'Personil'},
        ),
    ]
