# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-28 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utama', '0007_auto_20160625_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='personil',
            name='peran_utama',
            field=models.BooleanField(default=True, verbose_name='Peran utama?'),
        ),
    ]
