# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utama', '0008_personil_peran_utama'),
    ]

    operations = [
        migrations.AddField(
            model_name='format',
            name='kode',
            field=models.CharField(choices=[('TN', 'Technical Note'), ('TR', 'Technical Report'), ('TM', 'Technical Memorandum'), ('TD', 'Technical Document'), ('PCM', 'Progress Control and Monitoring'), ('IS', 'Instruction Sheet'), ('WS', 'Working Sheet'), ('DS', 'Decision Sheet')], default='', max_length=3, unique=True),
        ),
    ]
