# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-01 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ButirPendidikan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('butir', models.TextField(verbose_name='Butir Kegiatan')),
                ('kodebutir', models.CharField(max_length=50, verbose_name='Kode Butir')),
                ('hasil', models.CharField(max_length=100, verbose_name='Satuan Hasil')),
                ('angka', models.FloatField(verbose_name='Angka Kredit')),
                ('pelaksana', models.CharField(choices=[('', '----'), ('Pertama', 'Perekayasa Pertama'), ('Muda', 'Perekayasa Muda'), ('Madya', 'Perekayasa Madya'), ('Utama', 'Perekayasa Utama'), ('Semua', 'Semua Jenjang')], default='', max_length=10, verbose_name='Pelaksana')),
            ],
            options={
                'verbose_name_plural': 'Butir Pendidikan',
            },
        ),
        migrations.CreateModel(
            name='ButirPenunjang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('butir', models.TextField(verbose_name='Butir Kegiatan')),
                ('kodebutir', models.CharField(max_length=50, verbose_name='Kode Butir')),
                ('hasil', models.CharField(max_length=100, verbose_name='Satuan Hasil')),
                ('angka', models.FloatField(default=0.0, verbose_name='Angka Kredit')),
                ('pelaksana', models.CharField(choices=[('', '----'), ('Pertama', 'Perekayasa Pertama'), ('Muda', 'Perekayasa Muda'), ('Madya', 'Perekayasa Madya'), ('Utama', 'Perekayasa Utama'), ('Semua', 'Semua Jenjang')], default='', max_length=10, verbose_name='Pelaksana')),
            ],
            options={
                'verbose_name_plural': 'Butir Penunjang',
            },
        ),
        migrations.CreateModel(
            name='ButirPerekayasa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('butir', models.TextField(verbose_name='Butir Kegiatan')),
                ('kodebutir', models.CharField(max_length=50, verbose_name='Kode Butir')),
                ('hasil', models.CharField(max_length=100, verbose_name='Satuan Hasil')),
                ('angka', models.FloatField(default=0.0, verbose_name='Angka Kredit')),
                ('pelaksana', models.CharField(choices=[('', '----'), ('Pertama', 'Perekayasa Pertama'), ('Muda', 'Perekayasa Muda'), ('Madya', 'Perekayasa Madya'), ('Utama', 'Perekayasa Utama'), ('Semua', 'Semua Jenjang')], default='', max_length=10, verbose_name='Pelaksana')),
            ],
            options={
                'verbose_name_plural': 'Butir Perekayasa',
            },
        ),
        migrations.CreateModel(
            name='ButirProfesi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('butir', models.TextField(verbose_name='Butir Kegiatan')),
                ('kodebutir', models.CharField(max_length=50, verbose_name='Kode Butir')),
                ('hasil', models.CharField(max_length=100, verbose_name='Satuan Hasil')),
                ('angka', models.FloatField(default=0.0, verbose_name='Angka Kredit')),
                ('pelaksana', models.CharField(choices=[('', '----'), ('Pertama', 'Perekayasa Pertama'), ('Muda', 'Perekayasa Muda'), ('Madya', 'Perekayasa Madya'), ('Utama', 'Perekayasa Utama'), ('Semua', 'Semua Jenjang')], default='', max_length=10, verbose_name='Pelaksana')),
            ],
            options={
                'verbose_name_plural': 'Butir Pengembangan Profesi',
            },
        ),
    ]
