# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-01 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('butir', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='butirpendidikan',
            name='pelaksana',
            field=models.CharField(choices=[('', '----'), ('Pertama', 'Perekayasa Pertama'), ('Muda', 'Perekayasa Muda'), ('Madya', 'Perekayasa Madya'), ('Utama', 'Perekayasa Utama'), ('Semua', 'Semua Jenjang'), ('Pertama/Muda', 'Pertama/Muda'), ('Muda/Madya', 'Muda/Madya'), ('Muda/Madya', 'Muda/Madya'), ('Madya/Muda', 'Madya/Muda')], default='', max_length=20, verbose_name='Pelaksana'),
        ),
        migrations.AlterField(
            model_name='butirpenunjang',
            name='pelaksana',
            field=models.CharField(choices=[('', '----'), ('Pertama', 'Perekayasa Pertama'), ('Muda', 'Perekayasa Muda'), ('Madya', 'Perekayasa Madya'), ('Utama', 'Perekayasa Utama'), ('Semua', 'Semua Jenjang'), ('Pertama/Muda', 'Pertama/Muda'), ('Muda/Madya', 'Muda/Madya'), ('Muda/Madya', 'Muda/Madya'), ('Madya/Muda', 'Madya/Muda')], default='', max_length=20, verbose_name='Pelaksana'),
        ),
        migrations.AlterField(
            model_name='butirperekayasa',
            name='pelaksana',
            field=models.CharField(choices=[('', '----'), ('Pertama', 'Perekayasa Pertama'), ('Muda', 'Perekayasa Muda'), ('Madya', 'Perekayasa Madya'), ('Utama', 'Perekayasa Utama'), ('Semua', 'Semua Jenjang'), ('Pertama/Muda', 'Pertama/Muda'), ('Muda/Madya', 'Muda/Madya'), ('Muda/Madya', 'Muda/Madya'), ('Madya/Muda', 'Madya/Muda')], default='', max_length=20, verbose_name='Pelaksana'),
        ),
        migrations.AlterField(
            model_name='butirprofesi',
            name='pelaksana',
            field=models.CharField(choices=[('', '----'), ('Pertama', 'Perekayasa Pertama'), ('Muda', 'Perekayasa Muda'), ('Madya', 'Perekayasa Madya'), ('Utama', 'Perekayasa Utama'), ('Semua', 'Semua Jenjang'), ('Pertama/Muda', 'Pertama/Muda'), ('Muda/Madya', 'Muda/Madya'), ('Muda/Madya', 'Muda/Madya'), ('Madya/Muda', 'Madya/Muda')], default='', max_length=20, verbose_name='Pelaksana'),
        ),
    ]
