# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-13 05:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tugas', '0006_auto_20160813_1106'),
        ('logbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logbook',
            name='li',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tugas.LembarInstruksi', verbose_name='Lembar Instruksi'),
        ),
        migrations.AlterField(
            model_name='logbook',
            name='referensi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tugas.LembarKerja', verbose_name='Referensi'),
        ),
    ]
