# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-14 06:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0002_auto_20160813_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logbook',
            name='referensi',
        ),
    ]
