# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-14 23:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0003_remove_logbook_referensi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logbook',
            name='kegiatan',
        ),
        migrations.RemoveField(
            model_name='logbook',
            name='li',
        ),
        migrations.RemoveField(
            model_name='logbook',
            name='pemberi',
        ),
        migrations.RemoveField(
            model_name='logbook',
            name='pemeriksa',
        ),
        migrations.RemoveField(
            model_name='logbook',
            name='penerima',
        ),
        migrations.DeleteModel(
            name='Logbook',
        ),
    ]
