# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 02:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utama', '0010_auto_20160813_1110'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LembarKeputusan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(default='Lembar Keputusan', max_length=25, verbose_name='Jenis Tugas')),
                ('nomor', models.TextField(verbose_name='Nomor')),
                ('tanggal', models.DateField(verbose_name='Tanggal')),
                ('tingkatan', models.CharField(max_length=20, verbose_name='Tingkatan Rapat')),
                ('angka', models.FloatField(verbose_name='Angka Kredit')),
                ('uraian', models.TextField(blank=True, verbose_name='Uraian Singkat')),
                ('isi', models.TextField(verbose_name='Isi')),
                ('index', models.IntegerField(default=0, verbose_name='Index')),
                ('kegiatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utama.Kegiatan', verbose_name='Kegiatan')),
                ('pemberi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Pemberi Tugas')),
            ],
            options={
                'verbose_name_plural': 'Lembar Keputusan',
            },
        ),
    ]
