# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keputusan', '0002_auto_20160826_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='lembarkeputusan',
            name='butir',
            field=models.CharField(default='', max_length=20, verbose_name='Butir Kegiatan'),
        ),
    ]
