# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 04:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utama', '0007_auto_20160625_1623'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LembarInstruksi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(default='Lembar Instruksi', max_length=25, verbose_name='Jenis Tugas')),
                ('nomor', models.TextField(verbose_name='Nomor')),
                ('referensi', models.TextField(verbose_name='Referensi')),
                ('tanggal', models.DateField(verbose_name='Tanggal')),
                ('butir', models.CharField(max_length=20, verbose_name='Butir Kegiatan')),
                ('index', models.IntegerField(default=0, verbose_name='Index')),
                ('kegiatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utama.Kegiatan', verbose_name='Kegiatan')),
                ('pemberi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pemberi_tugas', to=settings.AUTH_USER_MODEL, verbose_name='Pemberi Tugas')),
                ('penerima', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penerima_tugas', to=settings.AUTH_USER_MODEL, verbose_name='Penerima Tugas')),
            ],
            options={
                'verbose_name_plural': 'Lembar Instruksi',
            },
        ),
        migrations.CreateModel(
            name='LembarKerja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(default='Lembar Kerja', max_length=25, verbose_name='Jenis Tugas')),
                ('nomor', models.TextField(verbose_name='Nomor')),
                ('referensi', models.TextField(verbose_name='Referensi')),
                ('tanggal', models.DateField(verbose_name='Tanggal')),
                ('butir', models.CharField(max_length=20, verbose_name='Butir Kegiatan')),
                ('index', models.IntegerField(default=0, verbose_name='Index')),
                ('kegiatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utama.Kegiatan', verbose_name='Kegiatan')),
                ('pemberi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pemberi_tugas_lk', to=settings.AUTH_USER_MODEL, verbose_name='Pemberi Tugas')),
                ('penerima', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penerima_tugas_lk', to=settings.AUTH_USER_MODEL, verbose_name='Penerima Tugas')),
            ],
            options={
                'verbose_name_plural': 'Lembar Kerja',
            },
        ),
    ]
