# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-21 04:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tugas', '0002_auto_20160630_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='lembarkerja',
            name='li',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tugas.LembarInstruksi', verbose_name='Lembar Instruksi'),
        ),
    ]
