# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-27 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tugas', '0003_lembarkerja_li'),
    ]

    operations = [
        migrations.AddField(
            model_name='lembarinstruksi',
            name='angka',
            field=models.FloatField(default=0.0, verbose_name='Angka Kredit'),
        ),
        migrations.AddField(
            model_name='lembarkerja',
            name='angka',
            field=models.FloatField(default=0.0, verbose_name='Angka Kredit'),
        ),
    ]
