# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-13 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tugas', '0005_lembarinstruksi_kesepakatan'),
    ]

    operations = [
        migrations.AddField(
            model_name='lembarinstruksi',
            name='uraian',
            field=models.TextField(blank=True, verbose_name='Uraian Singkat'),
        ),
        migrations.AddField(
            model_name='lembarkerja',
            name='uraian',
            field=models.TextField(blank=True, verbose_name='Uraian Singkat'),
        ),
    ]
