# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 03:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tugas', '0007_auto_20160815_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lembarkerja',
            name='lb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tugas.Logbook', verbose_name='Logbook'),
        ),
    ]
