# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tugas', '0008_auto_20160818_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='logbook',
            name='judul',
            field=models.CharField(default='', max_length=80, verbose_name='Judul'),
        ),
    ]
